import Link from "next/link";
import "./globals.css";
import Control from "./Control";

export const metadata = {
  title: "Web tutorials",
  description: "Generated by chobolevel",
};

export default async function RootLayout({ children }) {
  // 아래 fetch는 cache를 활용하지 않는다는 의미
  // fetch('url', next: { revalidate: 0 })
  // 아래 fetch 0초 동안 캐시를 유지한다는 의미
  const res = await fetch("http://localhost:9999/topics", {
    cache: "no-store",
  });
  const topics = await res.json();
  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic) => (
            <li key={topic.id}>
              <Link href={`/read/${topic.id}`}>{topic.title}</Link>
            </li>
          ))}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
